program DynaGeo;

uses
  Forms,
  Declar in 'Declar.pas',
  GlobVars in 'GlobVars.pas',
  SpeedBtnData in 'SpeedBtnData.pas',
  TBaum in 'TBaum.pas',
  mathlib in 'mathlib.pas',
  FileIO in 'FileIO.pas',
  FileIO2 in 'FileIO2.pas',
  Utility in 'Utility.pas',
  GeoTypes in 'GeoTypes.pas',
  GeoMakro in 'GeoMakro.pas',
  IniFDlg in 'IniFDlg.pas' {OptionsDlg},
  WertEing in 'WertEing.pas' {WertEingabeDlg},
  NameDlg in 'NameDlg.pas' {ObjNameDlg},
  OkayWin in 'OkayWin.pas' {OkayButton},
  ConstrWin in 'ConstrWin.pas' {ConstrTextWin},
  CoordWin in 'CoordWin.pas' {CoordDlg},
  TermEdit in 'TermEdit.pas' {TermEditDlg},
  PrnCfg in 'PrnCfg.pas' {PrinterCfgDlg},
  RegWin in 'RegWin.pas' {RegisterDlg},
  SelectWin in 'SelectWin.pas' {SelectDlg},
  CommentWin in 'CommentWin.pas' {TextWin},
  KonstEing in 'KonstEing.pas' {KonstEingabeDlg},
  KoordEing in 'KoordEing.pas' {KoordEingabeDlg},
  MakHelpShow in 'MakHelpShow.pas' {MakHelpWin},
  MakHelpEdit in 'MakHelpEdit.pas' {MakHelpDlg},
  SysMem in 'SysMem.pas' {SysMemWin},
  MenuCfgNew in 'MenuCfgNew.pas' {EditMenuConfigWin},
  MainWin in 'MainWin.pas' {Hauptfenster},
  FileProp in 'FileProp.pas' {FileProps},
  AboutWin in 'AboutWin.pas' {AboutBox},
  TermForm in 'TermForm.pas',
  Preview in 'Preview.pas' {PrintPreview},
  DragDrop in 'DragDrop.pas',
  RangeEdit in 'RangeEdit.pas' {RangeEditWin},
  Tables in 'Tables.pas',
  QuantPoint in 'QuantPoint.pas' {QuantPtWin},
  AniParams in 'AniParams.pas' {AniParamsWin},
  SelectXCmd in 'SelectXCmd.pas' {SelectXCmdForm},
  NetOptDlg in 'NetOptDlg.pas' {NetOptionsDlg},
  GeoEvents in 'GeoEvents.pas',
  ToolBarProc in 'Viewer\ToolBarProc.pas',
  GeoImage in 'GeoImage.pas',
  TagSelDlg in 'TagSelDlg.pas' {TagSelectDlg},
  RTF2HTMLConv in 'RTF2HTMLConv.pas',
  GeoVerging in 'GeoVerging.pas',
  GeoConic in 'GeoConic.pas',
  GroupWin in 'GroupWin.pas' {EditGroupWin},
  MemberWin in 'MemberWin.pas' {AddMemberWin},
  GeoGroup in 'GeoGroup.pas',
  GeoTransf in 'GeoTransf.pas',
  GeoLocLines in 'GeoLocLines.pas',
  GeoHelper in 'GeoHelper.pas',
  Unit_LGS in 'Unit_LGS.pas',
  AssAffAbb_1 in 'AssAffAbb_1.pas' {AffAbb_1_Dlg},
  AssAffAbb_2 in 'AssAffAbb_2.pas' {AffAbb_2_Dlg},
  AssAffAbb_3 in 'AssAffAbb_3.pas' {AffAbb_3_Dlg},
  AssAffAbb_2a in 'AssAffAbb_2a.pas' {AffAbb_2a_Dlg},
  AssAffAbb_2b in 'AssAffAbb_2b.pas' {AffAbb_2b_Dlg},
  AssAffAbb_2c in 'AssAffAbb_2c.pas' {AffAbb_2c_Dlg},
  AssAffAbb_2d in 'AssAffAbb_2d.pas' {AffAbb_2d_Dlg},
  AssAffAbb_2e in 'AssAffAbb_2e.pas' {AffAbb_2e_Dlg},
  AssAffAbb_3a in 'AssAffAbb_3a.pas' {AffAbb_3a_Dlg},
  AssAffAbb_3b in 'AssAffAbb_3b.pas' {AffAbb_3b_Dlg},
  LinkWin in 'LinkWin.pas' {EditLinkDlg},
  OKCheckConfWin in 'OKCheckConfWin.pas' {ConfigOKCheckDlg},
  ValidateResultWin in 'ValidateResultWin.pas' {ValidationResultWin},
  Symbols in 'Symbols.pas' {SymbolWin},
  AskUser1 in 'AskUser1.pas' {AskUser1Dlg},
  RiemannSum in 'RiemannSum.pas' {RiemannForm},
  EditMappingWin in 'EditMappingWin.pas' {EditMappingDlg},
  WerteTabelle in 'WerteTabelle.pas' {FunkTableWin},
  FileIO3 in 'FileIO3.pas',
  ExpertOptWin in 'ExpertOptWin.pas' {ExpertOptWin},
  HTMLDynaGeoXSettings in 'HTMLDynaGeoXSettings.pas' {HTMLDynaGeoXDataForm},
  HTMLDynaGeoJSettings in 'HTMLDynaGeoJSettings.pas' {HTMLDynaGeoJDataForm},
  xxcode in 'xxcode.pas',
  debuglog in 'debuglog.pas',
  ascrypt in 'ascrypt.pas',
  MyWebWin in 'MyWebWin.pas' {BrowserWin},
  MagnGlassWin in 'MagnGlassWin.pas' {MyMagnGlassWin},
  GameAngles1Dlg in 'GameAngles1Dlg.pas' {Angles1Dlg},
  GameRes1 in 'GameRes1.pas' {GameRes1Dlg},
  GameAngles2Dlg in 'GameAngles2Dlg.pas' {Angles2Dlg},
  FloatEdit in 'FloatEdit.pas',
  FormatEdit in 'FormatEdit.pas',
  FormatText in 'FormatText.pas',
  IntEdit in 'IntEdit.pas';

{$R *.RES}
{$R MYEUKLID.RES}

begin
  Application.Title := 'DynaGeo';
  Application.CreateForm(THauptfenster, Hauptfenster);
  Application.Run;
end.
