#define idh_cm_blinkbaseobj 3
#define idh_cm_refreshview 4
#define idh_cm_options 20
#define idh_cm_OkCheckRun 30

#define idh_cm_chordal 32
#define idh_cm_regpoly 33
#define idh_cm_polare 34
#define idh_cm_pol 35
#define idh_cm_SRichtTerm 36
#define idh_cm_CircleSLR 37

#define idh_cm_savedgjhtml 38
#define idh_cm_savedgxhtml 39
#define idh_cm_savegmahtml 40

#define idh_cm_verging 41
#define idh_cm_PtCoord 42
#define idh_cm_Strahl 43
#define idh_cm_Arc 44
#define idh_cm_Vector 45

#define idh_cm_MirrorAxisObj 47
#define idh_cm_MirrorCentreObj 49
#define idh_cm_MoveObj 51
#define idh_cm_RotateObj 53
#define idh_cm_StretchObj 55
#define idh_cm_MirrorPtAtCircle 56
#define idh_cm_DefAffin 57
#define idh_cm_MapObj 58
#define idh_cm_Map 59

#define idh_cm_NumberObj 78
#define idh_cm_TermObj 79
#define idh_cm_Area2Foregr 81
#define idh_cm_TogglePolyF 82
#define idh_cm_EditComment 88
#define idh_cm_Comment 90
#define idh_cm_Image 91
#define idh_cm_ConstrText 92
#define idh_cm_Group 94
#define idh_cm_DynaHelp 95
#define idh_cm_EditMap 96

#define idh_cm_New 101
#define idh_cm_Load 102
#define idh_cm_Save 103
#define idh_cm_SaveAs 104
#define idh_cm_PrnInit 105
#define idh_cm_Print 106
#define idh_cm_Exit 107
#define idh_cm_FileProp 108
#define idh_cm_PonLine 109

#define idh_cm_Work 110
#define idh_cm_PonGrid 111
#define idh_cm_ToggleVis 112
#define idh_cm_NameObj 113
#define idh_cm_DelObj 114
#define idh_cm_ZoomUp 115
#define idh_cm_ZoomDn 116
#define idh_cm_Slide 117
#define idh_cm_ShowAllObjs 118
#define idh_cm_EditDraw 119

#define idh_cm_Draw 120
#define idh_cm_PCreate 121
#define idh_cm_SCreate 122
#define idh_cm_GCreate 123
#define idh_cm_KCreate 124
#define idh_cm_DCreate 125
#define idh_cm_RCreate 126
#define idh_cm_FCreate 127
#define idh_cm_LCreate 128
#define idh_cm_MCreate 129
#define idh_cm_NCreate 131

#define idh_cm_schnitt 132
#define idh_cm_Mitte   133
#define idh_cm_MSenkr 135
#define idh_cm_whalb  136
#define idh_cm_parall 137
#define idh_cm_lot    138
#define idh_cm_GRicht 139

#define idh_cm_DefMakro 141
#define idh_cm_DelMakro 142
#define idh_cm_LoadMakro 143
#define idh_cm_SaveMakro 144
#define idh_cm_RunMakro 145
#define idh_cm_EditHlpMakro 146
#define idh_cm_ZoomReset 147

#define idh_cm_ShowGrowth 151
#define idh_cm_BindP2L 152
#define idh_cm_ReleaseP 153
#define idh_cm_MarkAngle 154
#define idh_cm_MeasureAngle 155
#define idh_cm_MeasureDist 156
#define idh_cm_TermInput 157
#define idh_cm_MakeLocLine 158
#define idh_cm_MeasureArea 159

#define idh_cm_HelpIndex 161
#define idh_cm_HelpBasics 164
#define idh_cm_HelpScreen 165
#define idh_cm_HelpKeyMouse 166
#define idh_cm_Licence 167
#define idh_cm_Register 168

// reserviert: 170 - 199 ; f&uuml;r Makros !!!

#define idh_cm_WriteToCB 201
#define idh_cm_Undo 203
#define idh_cm_UndoUndo 204
#define idh_cm_Preview 205
#define idh_cm_FillArea 206
#define idh_cm_CutArea 207

#define idh_cm_Animation 210
#define idh_cm_AnimaParams 212
#define idh_cm_RunAnimaBK 214
#define idh_cm_RunAnimaFD 215

#define idh_cm_Hauptleiste 220
#define idh_cm_Conic5p 221
#define idh_cm_EllipseF 222
#define idh_cm_EllipseS 223
#define idh_cm_EllipseK 224
#define idh_cm_ParabelF 225
#define idh_cm_ParabelT 226
#define idh_cm_HyperbelA 227
#define idh_cm_HyperbelF 228

#define idh_cm_graph 230
#define idh_cm_tangente 231
#define idh_cm_grapharea 233
#define idh_cm_riemann 234

#define idh_cm_PonGrid 236
#define idh_cm_Pt2BasePt 237
#define idh_cm_CombinePts 238
#define idh_cm_QuantP 239
#define idh_cm_Meas_Calc 240
#define idh_cm_CoordSys 241
#define idh_cm_FixPt 242
#define idh_cm_UnfixPt 243
#define idh_cm_Clip2Grid 244
#define idh_cm_BindTBox2Obj 245
#define idh_cm_ReleaseTBox 246

#define idh_spbtnRunMak 1217
#define idh_dgx_cmds 1218
#define idh_term 1219
#define idh_helpcontents 1220

#define idh_opt_start 1221
#define idh_opt_darst 1222
#define idh_opt_meas 1223
#define idh_opt_intern 1224
#define idh_opt_menu 1225
#define idh_opt_kons 1226
#define idh_opt_export 1227
#define idh_opt_map 1228
#define idh_opt_olines 1229
#define idh_opt_newcfg 1231

#define idh_toolbar 1240
#define idh_tool_main 1241
#define idh_tool_form 1242
#define idh_tool_constr 1243
#define idh_tool_map 1244
#define idh_tool_meas 1245
#define idh_tool_ani 1246
#define idh_tool_curves 1247

#define idh_menu_file 1281
#define idh_menu_edit 1282
#define idh_menu_draw 1283
#define idh_menu_constr 1284
#define idh_menu_map 1285
#define idh_menu_meas 1286
#define idh_menu_macro 1287
#define idh_menu_misc 1288
#define idh_menu_help 1289
#define idh_menu_conics 1290
#define idh_menu_view 1291

#define idh_OkCheck 1350
#define idh_cm_OkCheckCfg 1351
#define idh_cm_viewercmds 1352
#define idh_cm_geo3eck 1353
#define idh_boolterm 1354
#define idh_insthints 1355

#define idh_jump_pt 2001
#define idh_recursion 2002
#define idh_adminhints 2003
#define idh_altcmds 2004
#define idh_anibasics 2005
#define idh_dgj_html 2006
#define idh_dgj_include 2007
#define idh_dgj_winsys 2008
#define idh_dgxj_cmds 2009
#define idh_dgxj_work 2010
#define idh_dgx_dgj 2011
#define idh_dgx_html 2012
#define idh_dgx_include 2013
#define idh_dgx_winsys 2014
#define idh_dynadrawhtml 2015
#define idh_GroupBasics 2016
#define idh_DelBasics 2017
#define idh_LookInside 2018
#define idh_MakroDetails 2019
#define idh_MouseCursors 2020
#define idh_Newbies 2021
#define idh_NetOpt 2022
#define idh_NetHints 2023
#define idh_LocLineStandard 2024
#define idh_LocLineDyna 2025

#define idh_problems 2030
#define idh_prob_start 2031
#define idh_prob_skal 2032
#define idh_prob_print 2033
#define idh_prob_hh 2034
#define idh_prob_help 2035
#define idh_prob_export 2036
#define idh_prob_darst 2037

#define idh_PolyDetails 2040
#define idh_Reports 2041
#define idh_Relativities 2042
#define idh_Recursion 2043
#define idh_StartProc 2044
#define idh_StartParams 2045
#define idh_Hotkeys 2046
#define idh_StandardFunc 2047
#define idh_Required 2048
#define idh_Update 2049
#define idh_AngleDetails 2050
#define idh_menueditdraw 2051

#define idh_autochoose 27000
#define idh_basisobject 27001

#define idh_graph_varproblem 27005
#define idh_impress 27006
#define idh_contents 27007
#define idh_install 27008
#define idh_installhints 27009
#define idh_internals 27010
#define idh_intersect 27011
#define idh_jump_pt 27012
#define idh_coordsystem 27013
#define idh_deg_rad_problem 27014


